# 密码策略常量
PASSWORD_MIN_LENGTH = 8
PASSWORD_MAX_LENGTH = 128
PASSWORD_REQUIRE_UPPERCASE = True
PASSWORD_REQUIRE_LOWERCASE = True
PASSWORD_REQUIRE_DIGITS = True
PASSWORD_REQUIRE_SPECIAL_CHARS = True

# 登录限制常量
MAX_LOGIN_ATTEMPTS = 5
LOCKOUT_DURATION_MINUTES = 30
SESSION_TIMEOUT_MINUTES = 60

# 用户字段长度限制
USERNAME_MIN_LENGTH = 3
USERNAME_MAX_LENGTH = 50
EMAIL_MAX_LENGTH = 255
PHONE_MAX_LENGTH = 20
NICKNAME_MAX_LENGTH = 100
AVATAR_MAX_SIZE_KB = 1024  # 头像最大大小（KB）
AVATAR_IMAGE_TYPES = ['.jpg', '.jpeg', '.png', '.gif', '.webp'] # 头像图片类型

# 验证码相关
VERIFICATION_CODE_LENGTH = 6
VERIFICATION_CODE_EXPIRE_MINUTES = 5
VERIFICATION_CODE_MAX_ATTEMPTS = 3

# 安全相关
BCRYPT_ROUNDS = 12  # bcrypt加密轮数
TOKEN_BLACKLIST_PREFIX = "token_blacklist:"